### PR TITLE
Add method isStarted() to get the started status of the camera

### PR DESCRIPTION
**Pull request by alexander-fischer**

### CODE REVIEW

**Comment by Diolor** [comment]
By the time you call `onStart` we assure that the camera started. Therefore this should be handled in the client and there is no benefit in FA

**Comment by alexander-fischer** [comment]
The problem is that an exception is thrown, if onStart() is called, when camera is already started. It would be easier to return this boolean, so that it can be checked beforehand.

**Comment by Diolor** [comment]
You mean `IllegalStateException("Camera is already started!")` ?  As said above, if you call onStart it's the app's (and not this library's) responsibility to know weather or not you called onStart

**Comment by alexander-fischer** [comment]
Ok this is a stupid assumption, but I accept this as an answer.

**Pull request closed without merging**
