### PR TITLE
Wait capabilities + parameters to be created before obtaining them.

### LINKED ISSUE #170: getCurrentParameters()/getCapabilities().whenAvailable{} returns null if called too early
#### What are you trying to achieve or the steps to reproduce?
I'm trying to call Fotoapparat.getCurrentParameters().whenAvailable { ... } and Fotoapparat.getCapabilities().whenAvailable { ... } in my Activity's onStart().

```java
override fun onStart() {
  super.onStart()
  camera.start()
  camera.getCurrentParameters().whenAvailable { … }
  camera.getCapabilities().whenAvailable { … }
}
```

#### How did you initialize FA?
```java
override fun onCreate() {
  super.onCreate()
  …
  camera = Fotoapparat
    .with(this)
    .into(cameraView!!)
    .previewScaleType(ScaleType.CenterCrop)
    .photoResolution([custom_selector])
    .previewResolution([custom_selector])
    .lensPosition(single(LensPosition.Back))
    .focusMode(firstAvailable(
        continuousFocusPicture(),
        autoFocus(),
        fixed()))
    .flash(off())
    .frameProcessor { … }
    .previewFpsRange(highestFps())
    .cameraErrorCallback { … }
    .logger(logcat())
    .build()
}
```

#### What was the result you received?
Both calls return NULL and the log shows "Couldn't deliver pending result":
> 01-05 15:48:56.884 9089-9089/[package_name] D/Fotoapparat: Fotoapparat: getCapabilities
> 01-05 15:48:56.887 9089-13521/[package_name] D/Fotoapparat: CameraDevice: getParameters
> 01-05 15:48:56.888 9089-13094/[package_name] D/Fotoapparat: Couldn't deliver pending result.

#### What did you expect?
I expect the calls to return valid results and delay their async callbacks if the camera is still initializing.

#### Context:

* *FA version*: 2.0.2
* *Devices/APIs affected*: Samsung Galaxy S8 running Android 7.0.
* *Other Notes*: This used to work in version 1.5.0.

### PR DESCRIPTION
**Pull request by Diolor**
Fixes #170

### CODE REVIEW

**Comment by jpribble** [comment]
Thanks! I tested this and it's working for me now.

**Comment by Diolor** [comment]
Perfect @jpribble, then will merge it and release it in 2.1.

**Comment by jpribble** [comment]
I'm still seeing the "Couldn't deliver pending result" error message (and null returned) for getCurrentParameters() and getCapabilities() occasionally. It only happens about once in 20 launches but I've seen it occur about 4 times now. I'm testing with version 2.1.0. Do you know what could be causing that?

Logs:
> 01-10 23:00:25.270 27510-27741/[package_name] D/Fotoapparat: CameraDevice: getCapabilities$suspendImpl
> 01-10 23:00:25.289 27510-27741/[package_name] D/Fotoapparat: CameraDevice: updateParameters$suspendImpl
_**> 01-10 23:00:25.291 27510-27743/[package_name] D/Fotoapparat: Couldn't deliver pending result.**_
> 01-10 23:00:25.292 27510-27742/[package_name] D/Fotoapparat: CameraDevice: getCapabilities$suspendImpl
> 01-10 23:00:25.307 27510-27741/[package_name] D/Fotoapparat: New camera parameters are: CameraParameters

**Comment by Diolor** [comment]
Hmm potentially there is still some threading issue. 

Note that `null` means also some error happened on the device. E.g. there are Chinese devices which cannot return some capabilities, in that case they throw exceptions which is visible on this null.

Will reopen the issue since I think we are in the threading case.

**Comment by Diolor** [comment]
let's move conversation to #181

**Pull request merged**
